### ISSUE TITLE
Connect options with answers

### ISSUE THREAD

**Issue by subhojit777** [subhojit777/questionnaire-rs#34]
**Problem:**

Currently, `answers` table is connected with `questions` table via `question_id`. It expects a full answer like, _This is an answer to the question XYZ_. Since, questionnaire would actually work with options, therefore, ideally `answers` should be connected with `options`.

**Tasks:**

- [x] Make sure #4 is completed
- [x] Remove `title` from `answers`
- [x] Remove `question_id` from `answers`
- [x] Add `option_id` (FK to `options`) to `answers`
